name: 'Extract Version Information'
description: 'Extracts version, tag name, and image tags for consistent use across workflows'
inputs:
  workflow-type:
    description: 'Workflow type: main, pr, or release'
    required: true
  pr-number:
    description: 'PR number (only for pr workflow)'
    required: false
  release-tag:
    description: 'Release tag name (only for release workflow)'
    required: false
  image-suffix:
    description: 'Image suffix for variant (e.g., "" or "-distroless")'
    required: false
    default: ''
outputs:
  version:
    description: 'Semantic version (e.g., 1.2.3)'
    value: ${{ steps.extract.outputs.version }}
  tag-name:
    description: 'Git tag name (e.g., v1.2.3)'
    value: ${{ steps.extract.outputs.tag-name }}
  image-tag:
    description: 'Primary Docker image tag to use for scanning'
    value: ${{ steps.extract.outputs.image-tag }}
  short-sha:
    description: 'Short 7-character SHA'
    value: ${{ steps.extract.outputs.short-sha }}
runs:
  using: 'composite'
  steps:
    - name: Extract version information
      id: extract
      shell: bash
      run: |
        # Extract short SHA (first 7 characters)
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        echo "short-sha=${SHORT_SHA}" >> $GITHUB_OUTPUT

        case "${{ inputs.workflow-type }}" in
          release)
            # Release workflow: extract from release tag
            TAG_NAME="${{ inputs.release-tag }}"
            VERSION="${TAG_NAME#v}"
            IMAGE_TAG="${TAG_NAME}${{ inputs.image-suffix }}"
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "tag-name=${TAG_NAME}" >> $GITHUB_OUTPUT
            echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
            echo "Release: version=${VERSION}, tag=${TAG_NAME}, image=${IMAGE_TAG}"
            ;;

          pr)
            # PR workflow: use pr-NUMBER format
            VERSION="0.0.0-pr${{ inputs.pr-number }}"
            TAG_NAME="pr-${{ inputs.pr-number }}"
            IMAGE_TAG="pr-${{ inputs.pr-number }}${{ inputs.image-suffix }}"
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "tag-name=${TAG_NAME}" >> $GITHUB_OUTPUT
            echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
            echo "PR: version=${VERSION}, tag=${TAG_NAME}, image=${IMAGE_TAG}"
            ;;

          main)
            # Main branch: use main tag with date and run number
            DATE=$(date +%Y.%m.%d)
            VERSION="0.0.0-main.${DATE}.${{ github.run_number }}"
            TAG_NAME="main"
            IMAGE_TAG="main${{ inputs.image-suffix }}"
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            echo "tag-name=${TAG_NAME}" >> $GITHUB_OUTPUT
            echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
            echo "Main: version=${VERSION}, tag=${TAG_NAME}, image=${IMAGE_TAG}"
            ;;

          *)
            echo "Error: Invalid workflow-type '${{ inputs.workflow-type }}'. Must be: main, pr, or release"
            exit 1
            ;;
        esac
