# Copyright (c) 2025 Erick Bourgeois, firestoned
# SPDX-License-Identifier: MIT

.PHONY: help install test lint format docker-build docker-push deploy clean kind-create kind-deploy kind-test kind-cleanup docs docs-serve docs-rustdoc docs-clean crds crds-combined install-yaml integ-test-multi-tenancy sign-verify-install verify-image verify-binary sign-binary cargo-deny gitleaks gitleaks-install security-scan-local security-scan-quick security-scan-full install-git-hooks

REGISTRY ?= ghcr.io
IMAGE_NAME ?= firestoned/bindy
IMAGE_REPOSITORY ?= firestoned/bindy
IMAGE_TAG ?= latest-dev
NAMESPACE ?= dns-system
KIND_CLUSTER ?= bindy-test
KIND_CONTEXT ?= "kind-$(KIND_CLUSTER)"

# Security tool versions
GITLEAKS_VERSION ?= 8.21.2
TRIVY_VERSION ?= 0.69.3
SEMGREP_VERSION ?= 1.154.0
KUBESEC_VERSION ?= 2.14.2

help: ## Show this help message
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Available targets:'
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  %-20s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install: ## Install dependencies
	@echo "Ensure Rust toolchain is installed (rustup)."
	@rustup --version || echo "Install Rust from https://rustup.rs"

crds: ## Generate CRD YAML files from Rust types
	@echo "Generating CRD YAML files from src/crd.rs..."
	@cargo run --bin crdgen
	@echo "✓ CRD YAML files generated in deploy/crds/"

crds-combined: crds ## Generate combined crds.yaml file for releases
	@echo "Creating combined crds.yaml file..."
	@echo "# Copyright (c) 2025 Erick Bourgeois, firestoned" > deploy/crds.yaml
	@echo "# SPDX-License-Identifier: MIT" >> deploy/crds.yaml
	@echo "#" >> deploy/crds.yaml
	@echo "# Combined CRD definitions for Bindy" >> deploy/crds.yaml
	@echo "# Install with: kubectl apply -f https://github.com/firestoned/bindy/releases/latest/download/crds.yaml" >> deploy/crds.yaml
	@echo "#" >> deploy/crds.yaml
	@echo "# DO NOT EDIT MANUALLY - Generated from individual CRD files in deploy/crds/" >> deploy/crds.yaml
	@echo "---" >> deploy/crds.yaml
	@for file in deploy/crds/*.crd.yaml; do \
		echo "Processing $$file..."; \
		tail -n +4 "$$file" >> deploy/crds.yaml; \
		echo "---" >> deploy/crds.yaml; \
	done
	@echo "✓ Combined CRD file generated: deploy/crds.yaml"

install-yaml: crds-combined ## Generate single-file install.yaml (CRDs + RBAC + Deployment) for a given VERSION
	$(if $(VERSION),,$(error VERSION is required, e.g. make install-yaml VERSION=v0.1.0))
	@echo "Creating install.yaml for version $(VERSION)..."
	@{ \
		echo "# Copyright (c) 2025 Erick Bourgeois, firestoned"; \
		echo "# SPDX-License-Identifier: MIT"; \
		echo "#"; \
		echo "# Bindy $(VERSION) - single-file install"; \
		echo "# Install with: kubectl apply -f https://github.com/firestoned/bindy/releases/download/$(VERSION)/install.yaml"; \
		echo "#"; \
		echo "# DO NOT EDIT MANUALLY - Generated by 'make install-yaml VERSION=$(VERSION)'"; \
		echo ""; \
		echo "---"; \
		echo "# ============================================================"; \
		echo "# CRDs"; \
		echo "# ============================================================"; \
		for file in deploy/crds/*.crd.yaml; do \
			tail -n +4 "$$file"; \
			echo "---"; \
		done; \
		echo ""; \
		cat deploy/operator/namespace.yaml; \
		echo "# ============================================================"; \
		echo "# RBAC"; \
		echo "# ============================================================"; \
		cat deploy/rbac/serviceaccount.yaml; \
		cat deploy/rbac/role.yaml; \
		cat deploy/rbac/rolebinding.yaml; \
		echo ""; \
		echo "# ============================================================"; \
		echo "# Deployment"; \
		echo "# ============================================================"; \
		sed "s|image: ghcr.io/firestoned/bindy:.*|image: ghcr.io/firestoned/bindy:$(VERSION)|" deploy/operator/deployment.yaml; \
	} > deploy/install.yaml
	@echo "✓ install.yaml generated: deploy/install.yaml"

test: ## Run unit tests
	cargo test --all

test-integration: ## Run integration tests (requires Kubernetes)
	cargo test --test simple_integration -- --ignored

test-integ-multi-tenancy: ## Run multi-tenancy integration tests (requires Kubernetes)
	@echo "Running multi-tenancy integration tests..."
	@./tests/run_multi_tenancy_tests.sh

test-integ-cluster-provider: ## Run cluster provider resilience tests (requires Kubernetes)
	@echo "Running cluster provider resilience integration tests..."
	@chmod +x tests/cluster_provider_resilience_test.sh
	@./tests/cluster_provider_resilience_test.sh

test-all: test test-integration ## Run all tests (unit + integration)

test-lib: ## Run library tests only
	cargo test --lib

test-cov: ## Run tests with coverage using tarpaulin
	@command -v cargo-tarpaulin >/dev/null 2>&1 || { echo "Installing cargo-tarpaulin..."; cargo install cargo-tarpaulin; }
	cargo tarpaulin --out Html --output-dir coverage --exclude-files tests.rs --timeout 300

test-cov-view: test-cov ## Run coverage and open report
	@echo "Coverage report generated in coverage/tarpaulin-report.html"
	open coverage/tarpaulin-report.html 2>/dev/null || echo "Open coverage/tarpaulin-report.html manually"

test-cov-ci: ## Run coverage for CI (text output)
	@command -v cargo-tarpaulin >/dev/null 2>&1 || { echo "Installing cargo-tarpaulin..."; cargo install cargo-tarpaulin; }
	cargo tarpaulin --out Stdout --exclude-files tests.rs --timeout 300

# Security scanning targets
cargo-deny: ## Check dependencies for security, licenses, and supply chain issues
	@command -v cargo-deny >/dev/null 2>&1 || { echo "Installing cargo-deny..."; cargo install cargo-deny; }
	@echo "Running cargo-deny checks..."
	@cargo deny check --config .cargo/deny.toml

cargo-deny-json: ## Run cargo-deny with JSON output (for CI automation)
	@command -v cargo-deny >/dev/null 2>&1 || { echo "Installing cargo-deny..."; cargo install cargo-deny; }
	@echo "Running cargo-deny checks (JSON output)..."
	@cargo deny --format json check --config .cargo/deny.toml

gitleaks-install: ## Install gitleaks from GitHub with checksum verification
	@if ! command -v gitleaks >/dev/null 2>&1; then \
		echo "Installing gitleaks v$(GITLEAKS_VERSION)..."; \
		OS=$$(uname -s | tr '[:upper:]' '[:lower:]'); \
		ARCH=$$(uname -m); \
		case "$$ARCH" in \
			x86_64) ARCH="x64" ;; \
			aarch64|arm64) ARCH="arm64" ;; \
		esac; \
		PLATFORM="$${OS}_$${ARCH}"; \
		TARBALL="gitleaks_$(GITLEAKS_VERSION)_$${PLATFORM}.tar.gz"; \
		BASE_URL="https://github.com/gitleaks/gitleaks/releases/download/v$(GITLEAKS_VERSION)"; \
		echo "Downloading gitleaks for $${PLATFORM}..."; \
		curl -sSL -o /tmp/$${TARBALL} $${BASE_URL}/$${TARBALL}; \
		echo "Downloading checksums..."; \
		curl -sSL -o /tmp/gitleaks_checksums.txt $${BASE_URL}/gitleaks_$(GITLEAKS_VERSION)_checksums.txt; \
		echo "Verifying checksum..."; \
		cd /tmp && grep "$${TARBALL}" gitleaks_checksums.txt > checksum_file.txt; \
		if [ "$$OS" = "darwin" ]; then \
			shasum -a 256 -c checksum_file.txt || { echo "Checksum verification failed!"; rm -f $${TARBALL} gitleaks_checksums.txt checksum_file.txt; exit 1; }; \
		else \
			sha256sum -c checksum_file.txt || { echo "Checksum verification failed!"; rm -f $${TARBALL} gitleaks_checksums.txt checksum_file.txt; exit 1; }; \
		fi; \
		tar -xzf /tmp/$${TARBALL} -C /tmp; \
		if [ -w /usr/local/bin ]; then \
			mv /tmp/gitleaks /usr/local/bin/; \
		else \
			echo "Installing to ~/.local/bin (need sudo for /usr/local/bin)..."; \
			mkdir -p ~/.local/bin; \
			mv /tmp/gitleaks ~/.local/bin/; \
			export PATH="$$HOME/.local/bin:$$PATH"; \
		fi; \
		rm -f /tmp/$${TARBALL} /tmp/gitleaks_checksums.txt /tmp/checksum_file.txt; \
		echo "✓ Gitleaks v$(GITLEAKS_VERSION) installed successfully"; \
	else \
		echo "✓ Gitleaks already installed"; \
	fi

gitleaks: gitleaks-install ## Scan for hardcoded secrets and credentials
	@echo "Scanning for secrets with gitleaks..."
	@gitleaks detect --source . --verbose --redact

trivy-install: ## Install Trivy scanner from GitHub with checksum verification
	@if ! command -v trivy >/dev/null 2>&1; then \
		echo "Installing Trivy v$(TRIVY_VERSION)..."; \
		OS=$$(uname -s); \
		ARCH=$$(uname -m); \
		case "$$ARCH" in \
			x86_64) ARCH="64bit" ;; \
			aarch64|arm64) ARCH="ARM64" ;; \
		esac; \
		case "$$OS" in \
			Linux) PLATFORM="Linux-$${ARCH}" ;; \
			Darwin) PLATFORM="macOS-$${ARCH}" ;; \
			*) echo "Unsupported platform: $$OS"; exit 1 ;; \
		esac; \
		TARBALL="trivy_$(TRIVY_VERSION)_$${PLATFORM}.tar.gz"; \
		BASE_URL="https://github.com/aquasecurity/trivy/releases/download/v$(TRIVY_VERSION)"; \
		echo "Downloading Trivy for $${PLATFORM}..."; \
		curl -sSL -o /tmp/$${TARBALL} $${BASE_URL}/$${TARBALL}; \
		echo "Downloading checksums..."; \
		curl -sSL -o /tmp/trivy_checksums.txt $${BASE_URL}/trivy_$(TRIVY_VERSION)_checksums.txt; \
		echo "Verifying checksum..."; \
		EXPECTED_CHECKSUM=$$(grep "$${TARBALL}" /tmp/trivy_checksums.txt | awk '{print $$1}'); \
		if [ -z "$$EXPECTED_CHECKSUM" ]; then \
			echo "Error: Could not find checksum for $${TARBALL}"; \
			rm -f /tmp/$${TARBALL} /tmp/trivy_checksums.txt; \
			exit 1; \
		fi; \
		if [ "$$OS" = "Darwin" ]; then \
			ACTUAL_CHECKSUM=$$(shasum -a 256 /tmp/$${TARBALL} | awk '{print $$1}'); \
		else \
			ACTUAL_CHECKSUM=$$(sha256sum /tmp/$${TARBALL} | awk '{print $$1}'); \
		fi; \
		if [ "$$EXPECTED_CHECKSUM" != "$$ACTUAL_CHECKSUM" ]; then \
			echo "Checksum verification failed!"; \
			echo "Expected: $$EXPECTED_CHECKSUM"; \
			echo "Actual:   $$ACTUAL_CHECKSUM"; \
			rm -f /tmp/$${TARBALL} /tmp/trivy_checksums.txt; \
			exit 1; \
		fi; \
		echo "✓ Checksum verified"; \
		tar -xzf /tmp/$${TARBALL} -C /tmp; \
		if [ -w /usr/local/bin ]; then \
			mv /tmp/trivy /usr/local/bin/; \
		else \
			echo "Installing to ~/.local/bin (need sudo for /usr/local/bin)..."; \
			mkdir -p ~/.local/bin; \
			mv /tmp/trivy ~/.local/bin/; \
			export PATH="$$HOME/.local/bin:$$PATH"; \
		fi; \
		rm -f /tmp/$${TARBALL} /tmp/trivy_checksums.txt; \
		echo "✓ Trivy v$(TRIVY_VERSION) installed successfully"; \
	else \
		echo "✓ Trivy already installed: $$(trivy --version)"; \
	fi

trivy-image: trivy-install ## Scan container image for vulnerabilities (usage: make trivy-image IMAGE_TAG=latest)
	@if [ -z "$(IMAGE_TAG)" ]; then \
		echo "Error: IMAGE_TAG parameter required. Usage: make trivy-image IMAGE_TAG=latest"; \
		exit 1; \
	fi
	@echo "Scanning container image: $(REGISTRY)/$(IMAGE_REPOSITORY):$(IMAGE_TAG)"
	@trivy image \
		--severity HIGH,CRITICAL \
		--format table \
		--exit-code 0 \
		$(REGISTRY)/$(IMAGE_REPOSITORY):$(IMAGE_TAG)

trivy-image-sarif: trivy-install ## Scan container image and output SARIF (for GitHub Security)
	@if [ -z "$(IMAGE_TAG)" ]; then \
		echo "Error: IMAGE_TAG parameter required. Usage: make trivy-image-sarif IMAGE_TAG=latest"; \
		exit 1; \
	fi
	@echo "Scanning container image: $(REGISTRY)/$(IMAGE_REPOSITORY):$(IMAGE_TAG)"
	@trivy image \
		--severity HIGH,CRITICAL \
		--format sarif \
		--output trivy-image-results.sarif \
		$(REGISTRY)/$(IMAGE_REPOSITORY):$(IMAGE_TAG)
	@echo "✓ SARIF results written to trivy-image-results.sarif"

trivy-fs: trivy-install ## Scan filesystem for vulnerabilities and misconfigurations
	@echo "Scanning filesystem for vulnerabilities..."
	@trivy fs \
		--severity HIGH,CRITICAL \
		--scanners vuln,secret,misconfig \
		--format table \
		--exit-code 0 \
		.

trivy-fs-sarif: trivy-install ## Scan filesystem and output SARIF (for GitHub Security)
	@echo "Scanning filesystem for vulnerabilities..."
	@trivy fs \
		--severity HIGH,CRITICAL \
		--scanners vuln,secret,misconfig \
		--format sarif \
		--output trivy-fs-results.sarif \
		.
	@echo "✓ SARIF results written to trivy-fs-results.sarif"

trivy-k8s: trivy-install ## Scan Kubernetes manifests for misconfigurations
	@echo "Scanning Kubernetes manifests in deploy/..."
	@trivy config \
		--severity HIGH,CRITICAL \
		--format table \
		--exit-code 0 \
		deploy/
	@echo ""
	@echo "Scanning Kubernetes manifests in examples/..."
	@trivy config \
		--severity HIGH,CRITICAL \
		--format table \
		--exit-code 0 \
		examples/

trivy-k8s-sarif: trivy-install ## Scan Kubernetes manifests and output SARIF (for GitHub Security)
	@echo "Scanning Kubernetes manifests in deploy/..."
	@trivy config \
		--severity HIGH,CRITICAL \
		--format sarif \
		--output trivy-k8s-deploy-results.sarif \
		deploy/
	@echo "✓ SARIF results written to trivy-k8s-deploy-results.sarif"
	@echo ""
	@echo "Scanning Kubernetes manifests in examples/..."
	@trivy config \
		--severity HIGH,CRITICAL \
		--format sarif \
		--output trivy-k8s-examples-results.sarif \
		examples/
	@echo "✓ SARIF results written to trivy-k8s-examples-results.sarif"

trivy-all: trivy-fs trivy-k8s ## Run all Trivy security scans (filesystem + Kubernetes manifests)
	@echo "✓ All Trivy scans completed"

semgrep-install: ## Install Semgrep via pipx (isolated Python app installer)
	@if ! command -v semgrep >/dev/null 2>&1; then \
		echo "Installing Semgrep v$(SEMGREP_VERSION) via pipx..."; \
		if ! command -v python3 >/dev/null 2>&1; then \
			echo "Error: Python 3 is required but not found. Please install Python 3.10 or later."; \
			exit 1; \
		fi; \
		if ! command -v pipx >/dev/null 2>&1; then \
			echo "Error: pipx is required but not found."; \
			echo "Install pipx with: python3 -m pip install --user pipx && python3 -m pipx ensurepath"; \
			echo "Or see: https://pipx.pypa.io/stable/installation/"; \
			exit 1; \
		fi; \
		pipx install "semgrep==$(SEMGREP_VERSION)"; \
		if ! command -v semgrep >/dev/null 2>&1; then \
			echo "⚠️  Semgrep installed but not found in PATH."; \
			echo "  Run: pipx ensurepath"; \
			echo "  Then restart your shell or run: source ~/.bashrc (or ~/.zshrc)"; \
			exit 1; \
		else \
			echo "✓ Semgrep v$(SEMGREP_VERSION) installed successfully"; \
		fi; \
	else \
		INSTALLED_VERSION=$$(semgrep --version | head -n1 | awk '{print $$1}'); \
		echo "✓ Semgrep already installed: $$INSTALLED_VERSION"; \
		if [ "$$INSTALLED_VERSION" != "$(SEMGREP_VERSION)" ]; then \
			echo "  (target version: $(SEMGREP_VERSION))"; \
		fi; \
	fi

semgrep: semgrep-install ## Run Semgrep SAST analysis with Rust, Kubernetes, and Docker rulesets
	@echo "Running Semgrep security analysis..."
	@semgrep scan \
		--config=p/rust \
		--config=p/kubernetes \
		--config=p/docker \
		--severity=ERROR \
		--severity=WARNING \
		--exclude='target/' \
		--exclude='*.lock' \
		--exclude='docs/' \
		--metrics=off \
		. || echo "⚠️  Semgrep found potential issues (see output above)"
	@echo "✓ Semgrep scan completed"

semgrep-sarif: semgrep-install ## Run Semgrep and output SARIF format (for GitHub Security)
	@echo "Running Semgrep security analysis (SARIF output)..."
	@semgrep scan \
		--config=p/rust \
		--config=p/kubernetes \
		--config=p/docker \
		--severity=ERROR \
		--severity=WARNING \
		--exclude='target/' \
		--exclude='*.lock' \
		--exclude='docs/' \
		--sarif \
		--output=semgrep-results.sarif \
		--metrics=off \
		. || true
	@echo "✓ SARIF results written to semgrep-results.sarif"

kubesec-install: ## Install Kubesec from GitHub with checksum verification
	@if ! command -v kubesec >/dev/null 2>&1; then \
		echo "Installing Kubesec v$(KUBESEC_VERSION)..."; \
		OS=$$(uname -s); \
		ARCH=$$(uname -m); \
		case "$$ARCH" in \
			x86_64) ARCH="amd64" ;; \
			aarch64|arm64) ARCH="arm64" ;; \
		esac; \
		case "$$OS" in \
			Linux) PLATFORM="linux_$${ARCH}" ;; \
			Darwin) PLATFORM="darwin_$${ARCH}" ;; \
			*) echo "Unsupported platform: $$OS"; exit 1 ;; \
		esac; \
		TARBALL="kubesec_$${PLATFORM}.tar.gz"; \
		BASE_URL="https://github.com/controlplaneio/kubesec/releases/download/v$(KUBESEC_VERSION)"; \
		echo "Downloading Kubesec for $${PLATFORM}..."; \
		curl -sSL -o /tmp/$${TARBALL} $${BASE_URL}/$${TARBALL}; \
		echo "Downloading checksums..."; \
		curl -sSL -o /tmp/kubesec_checksums.txt $${BASE_URL}/kubesec_checksums.txt; \
		echo "Verifying checksum..."; \
		EXPECTED_CHECKSUM=$$(grep "$${TARBALL}" /tmp/kubesec_checksums.txt | awk '{print $$1}'); \
		if [ -z "$$EXPECTED_CHECKSUM" ]; then \
			echo "Error: Could not find checksum for $${TARBALL}"; \
			rm -f /tmp/$${TARBALL} /tmp/kubesec_checksums.txt; \
			exit 1; \
		fi; \
		if [ "$$OS" = "Darwin" ]; then \
			ACTUAL_CHECKSUM=$$(shasum -a 256 /tmp/$${TARBALL} | awk '{print $$1}'); \
		else \
			ACTUAL_CHECKSUM=$$(sha256sum /tmp/$${TARBALL} | awk '{print $$1}'); \
		fi; \
		if [ "$$EXPECTED_CHECKSUM" != "$$ACTUAL_CHECKSUM" ]; then \
			echo "Checksum verification failed!"; \
			echo "Expected: $$EXPECTED_CHECKSUM"; \
			echo "Actual:   $$ACTUAL_CHECKSUM"; \
			rm -f /tmp/$${TARBALL} /tmp/kubesec_checksums.txt; \
			exit 1; \
		fi; \
		echo "✓ Checksum verified"; \
		tar -xzf /tmp/$${TARBALL} -C /tmp; \
		if [ -w /usr/local/bin ]; then \
			mv /tmp/kubesec /usr/local/bin/; \
		else \
			echo "Installing to ~/.local/bin (need sudo for /usr/local/bin)..."; \
			mkdir -p ~/.local/bin; \
			mv /tmp/kubesec ~/.local/bin/; \
			export PATH="$$HOME/.local/bin:$$PATH"; \
		fi; \
		rm -f /tmp/$${TARBALL} /tmp/kubesec_checksums.txt; \
		echo "✓ Kubesec v$(KUBESEC_VERSION) installed successfully"; \
	else \
		echo "✓ Kubesec already installed: $$(kubesec version 2>/dev/null || echo 'version unknown')"; \
	fi

kubesec: kubesec-install ## Scan Kubernetes manifests with Kubesec for security best practices
	@echo "Scanning Kubernetes manifests with Kubesec..."
	@TOTAL=0; CRITICAL=0; WARNING=0; \
	for file in deploy/operator/*.yaml deploy/rbac/*.yaml examples/*.yaml; do \
		if [ -f "$$file" ]; then \
			echo "Scanning $$file..."; \
			RESULT=$$(kubesec scan "$$file" 2>&1); \
			SCORE=$$(echo "$$RESULT" | grep -o '"score":[0-9-]*' | head -1 | cut -d':' -f2 || echo ""); \
			if [ -n "$$SCORE" ]; then \
				if [ "$$SCORE" -lt 0 ]; then \
					echo "  ⚠️  Critical issues (Score: $$SCORE)"; \
					CRITICAL=$$((CRITICAL + 1)); \
				elif [ "$$SCORE" -lt 5 ]; then \
					echo "  ⚠️  Needs improvement (Score: $$SCORE)"; \
					WARNING=$$((WARNING + 1)); \
				else \
					echo "  ✓ Good (Score: $$SCORE)"; \
				fi; \
			else \
				echo "  ℹ️  CRD or multi-resource file (not scored)"; \
			fi; \
			TOTAL=$$((TOTAL + 1)); \
		fi; \
	done; \
	echo ""; \
	echo "Kubesec scan summary:"; \
	echo "  - Total files scanned: $$TOTAL"; \
	echo "  - Critical issues: $$CRITICAL"; \
	echo "  - Warnings: $$WARNING"; \
	echo "✓ Kubesec scan completed"

license-check: ## Check all dependency licenses against policy (fails on GPL/AGPL/SSPL)
	@command -v cargo-license >/dev/null 2>&1 || { echo "Installing cargo-license..."; cargo install cargo-license; }
	@echo "Checking dependency licenses..."
	@VIOLATIONS=$$(cargo license --json 2>/dev/null | \
		jq -r '.[] | select(.license | test("(^| )GPL|AGPL|SSPL|EUPL|CDDL"; "i")) | "\(.name) \(.version): \(.license)"'); \
	if [ -n "$$VIOLATIONS" ]; then \
		echo "❌ Prohibited license(s) found:"; \
		echo "$$VIOLATIONS"; \
		exit 1; \
	else \
		echo "✓ All dependency licenses are compliant"; \
	fi

license-report: ## Generate full license report for all dependencies (outputs licenses.json)
	@command -v cargo-license >/dev/null 2>&1 || { echo "Installing cargo-license..."; cargo install cargo-license; }
	@echo "Generating license report..."
	@cargo license --json > licenses.json
	@echo "✓ License report written to licenses.json"
	@echo ""
	@echo "License Summary:"
	@cargo license 2>/dev/null | sort | uniq -c | sort -rn | head -20

security-scan-local: cargo-deny gitleaks ## Run local security scans (pre-commit)
	@echo "✓ Local security scans completed"

security-scan-quick: cargo-deny gitleaks license-check ## Run quick security scans (for CI)
	@echo "✓ Quick security scans completed"

security-scan-full: cargo-deny gitleaks trivy-all semgrep kubesec license-check ## Run all security scans (Phase 1-5 complete)
	@echo "✓ All security scans completed"

install-git-hooks: ## Install git pre-commit hooks (gitleaks secret scanning)
	@echo "Installing git pre-commit hooks..."
	@if [ ! -d .git ]; then \
		echo "Error: Not a git repository"; \
		exit 1; \
	fi
	@ln -sf ../../scripts/pre-commit-gitleaks.sh .git/hooks/pre-commit
	@chmod +x .git/hooks/pre-commit
	@echo "✓ Git hooks installed successfully"
	@echo "  - Pre-commit hook: gitleaks secret scanning"
	@echo ""
	@echo "To bypass the hook (NOT RECOMMENDED): git commit --no-verify"

lint: ## Run linting and checks
	cargo fmt -- --check
	cargo clippy -- -D warnings

format: ## Format code
	cargo fmt

docker-build: ## Build Docker image
	./scripts/build-docker-fast.sh local

docker-build-kind:
	KIND_CLUSTER=$(KIND_CLUSTER) ./scripts/build-docker-fast.sh kind

docker-build-no-cache-kind:
	KIND_CLUSTER=$(KIND_CLUSTER) ./scripts/build-docker-fast.sh --no-cache kind

docker-push: ## Push Docker image
	docker push $(REGISTRY)/$(IMAGE_NAME):$(IMAGE_TAG)

deploy-crds: ## Deploy CRDs
	kubectl create -f deploy/crds/

deploy-rbac: ## Deploy RBAC resources
	kubectl create namespace $(NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	kubectl apply -f deploy/rbac/ -n $(NAMESPACE)

deploy-operator: ## Deploy operator
	kubectl apply -f deploy/operator/ -n $(NAMESPACE)

deploy: deploy-crds deploy-rbac deploy-operator ## Deploy everything

undeploy: ## Remove operator
	kubectl delete -f deploy/operator/ -n $(NAMESPACE) || true
	kubectl delete -f deploy/rbac/ -n $(NAMESPACE) || true
	kubectl delete -f deploy/crds/ || true

clean: ## Clean build artifacts
	cargo clean
	rm -rf target/

run-local: ## Run operator locally
	RUST_LOG=info cargo run --release

# Kind cluster targets
kind-create: ## Create Kind cluster for testing
	kind create cluster --config deploy/kind-config.yaml --name $(KIND_CLUSTER)

kind-deploy: ## Deploy to Kind cluster (creates cluster, builds, and deploys)
	./deploy/kind-deploy.sh

kind-test: ## Run tests on Kind cluster
	./deploy/kind-test.sh

kind-integration-test: ## Run full integration test suite (local build)
	./tests/integration_test.sh

kind-integration-test-ci: ## Run integration tests in CI mode (requires IMAGE_TAG env var)
	@echo "Running integration tests in CI mode..."
	@command -v kind >/dev/null 2>&1 || { echo "Error: kind not found. Install from https://kind.sigs.k8s.io/docs/user/quick-start/"; exit 1; }
	@command -v kubectl >/dev/null 2>&1 || { echo "Error: kubectl not found"; exit 1; }
	@echo "Checking for existing Kind cluster..."
	@kind delete cluster --name $(KIND_CLUSTER) 2>/dev/null || true
	@echo "Creating Kind cluster..."
	@kind create cluster --name $(KIND_CLUSTER) --config deploy/kind-config.yaml
	@kubectl cluster-info --context $(KIND_CONTEXT)
	@echo "Installing CRDs..."
	@kubectl --context $(KIND_CONTEXT) create namespace $(NAMESPACE) || true
	@kubectl --context $(KIND_CONTEXT) replace --force -f deploy/crds/ 2>/dev/null || kubectl --context $(KIND_CONTEXT) create -f deploy/crds/
	@echo "Installing RBAC..."
	@kubectl --context $(KIND_CONTEXT) apply -f deploy/rbac/
	@echo "Deploying operator with image: $(REGISTRY)/$(IMAGE_REPOSITORY):$(IMAGE_TAG)"
	@sed "s|ghcr.io/firestoned/bindy:latest|$(REGISTRY)/$(IMAGE_REPOSITORY):$(IMAGE_TAG)|g" deploy/operator/deployment.yaml | kubectl --context $(KIND_CONTEXT) apply -f -
	@kubectl --context $(KIND_CONTEXT) wait --for=condition=available --timeout=300s deployment/bindy -n $(NAMESPACE)
	@echo ""
	@echo "================================================"
	@echo "  Running Simple Integration Tests"
	@echo "================================================"
	@chmod +x tests/integration_test.sh
	@CLUSTER_NAME=$(KIND_CLUSTER) tests/integration_test.sh --image "$(REGISTRY)/$(IMAGE_REPOSITORY):$(IMAGE_TAG)" --skip-deploy || { echo "Simple integration tests failed"; kind delete cluster --name $(KIND_CLUSTER) || true; exit 1; }
	@echo ""
	@echo "================================================"
	@echo "  Running Multi-Tenancy Integration Tests"
	@echo "================================================"
	@chmod +x tests/run_multi_tenancy_tests.sh
	@CLUSTER_NAME=$(KIND_CLUSTER) tests/run_multi_tenancy_tests.sh || { echo "Multi-tenancy integration tests failed"; kind delete cluster --name $(KIND_CLUSTER) || true; exit 1; }
	@echo ""
	@echo "Cleaning up Kind cluster..."
	@kind delete cluster --name $(KIND_CLUSTER) || true
	@echo "✓ All integration tests completed successfully"

kind-cleanup: ## Delete Kind cluster
	./deploy/kind-cleanup.sh

kind-logs: ## Show operator logs from Kind cluster
	kubectl logs -n $(NAMESPACE) -l app=bindy -f --context kind-$(KIND_CLUSTER)

# Build targets
build: ## Build the Rust binary
	cargo build --release

build-debug: ## Build the Rust binary in debug mode
	cargo build

build-aarch64-linux-debug: ## Build the Rust binary in debug mode
	CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-unknown-linux-gnu-gcc \
	cargo build --target aarch64-unknown-linux-gnu

# Documentation targets
docs: export PATH := $(HOME)/.local/bin:$(HOME)/.cargo/bin:$(PATH)
docs: ## Build all documentation (MkDocs + rustdoc + CRD API reference)
	@echo "Building all documentation..."
	@echo "Checking Poetry installation..."
	@command -v poetry >/dev/null 2>&1 || { echo "Error: Poetry not found. Install with: curl -sSL https://install.python-poetry.org | python3 -"; exit 1; }
	@echo "Ensuring documentation dependencies are installed..."
	@cd docs && poetry install --no-interaction --quiet
	@echo "Generating CRD API reference documentation..."
	@cargo run --bin crddoc > docs/src/reference/api.md
	@echo "Building rustdoc API documentation..."
	@cargo doc --no-deps --all-features
	@echo "Building MkDocs documentation..."
	@cd docs && poetry run mkdocs build
	@echo "Copying rustdoc into documentation..."
	@mkdir -p docs/site/rustdoc
	@cp -r target/doc/* docs/site/rustdoc/
	@echo "Creating rustdoc index redirect..."
	@echo '<!DOCTYPE html>' > docs/site/rustdoc/index.html
	@echo '<html>' >> docs/site/rustdoc/index.html
	@echo '<head>' >> docs/site/rustdoc/index.html
	@echo '    <meta charset="utf-8">' >> docs/site/rustdoc/index.html
	@echo '    <title>Bindy API Documentation</title>' >> docs/site/rustdoc/index.html
	@echo '    <meta http-equiv="refresh" content="0; url=bindy/index.html">' >> docs/site/rustdoc/index.html
	@echo '</head>' >> docs/site/rustdoc/index.html
	@echo '<body>' >> docs/site/rustdoc/index.html
	@echo '    <p>Redirecting to <a href="bindy/index.html">Bindy API Documentation</a>...</p>' >> docs/site/rustdoc/index.html
	@echo '</body>' >> docs/site/rustdoc/index.html
	@echo '</html>' >> docs/site/rustdoc/index.html
	@echo "✓ Documentation built successfully in docs/site/"
	@echo "  - User guide: docs/site/index.html"
	@echo "  - API reference: docs/site/rustdoc/bindy/index.html"

docs-serve: export PATH := $(HOME)/.local/bin:$(PATH)
docs-serve: ## Serve documentation locally with live reload (MkDocs)
	@echo "Starting MkDocs development server with live reload..."
	@command -v poetry >/dev/null 2>&1 || { echo "Error: Poetry not found. Run ./scripts/setup-docs-env.sh first."; exit 1; }
	@echo "Ensuring documentation dependencies are installed..."
	@cd docs && poetry install --no-interaction --quiet
	@echo ""
	@echo "Documentation server starting at http://127.0.0.1:8000"
	@echo "Live reload enabled - changes will auto-refresh your browser"
	@echo ""
	@echo "Watching:"
	@echo "  - Documentation content: docs/src/"
	@echo "  - Configuration: docs/mkdocs.yml"
	@echo "  - Theme files: docs/theme/"
	@echo ""
	@echo "Press Ctrl+C to stop"
	@echo ""
	@cd docs && poetry run mkdocs serve --watch-theme --livereload

docs-rustdoc: ## Build and open rustdoc API documentation only
	@echo "Building rustdoc API documentation..."
	@cargo doc --no-deps --all-features --open

docs-clean: ## Clean documentation build artifacts
	@echo "Cleaning documentation build artifacts..."
	@rm -rf docs/site/
	@rm -rf target/doc/
	@rm -rf docs/.venv/
	@rm -rf docs/poetry.lock
	@echo "✓ Documentation artifacts cleaned"

# Signing and verification targets
sign-verify-install: ## Install Cosign for signing and verification
	@echo "Checking for Cosign installation..."
	@if command -v cosign >/dev/null 2>&1; then \
		echo "✓ Cosign already installed: $$(cosign version)"; \
	else \
		echo "Installing Cosign..."; \
		if [ "$$(uname)" = "Darwin" ]; then \
			brew install cosign; \
		else \
			LATEST_VERSION=$$(curl -s https://api.github.com/repos/sigstore/cosign/releases/latest | grep tag_name | cut -d '"' -f 4); \
			curl -Lo /tmp/cosign "https://github.com/sigstore/cosign/releases/download/$${LATEST_VERSION}/cosign-linux-amd64"; \
			chmod +x /tmp/cosign; \
			sudo mv /tmp/cosign /usr/local/bin/; \
		fi; \
		echo "✓ Cosign installed successfully"; \
	fi

verify-image: ## Verify container image signature (usage: make verify-image IMAGE_TAG=v0.1.0)
	@echo "Verifying signature for image: $(REGISTRY)/$(IMAGE_REPOSITORY):$(IMAGE_TAG)"
	@command -v cosign >/dev/null 2>&1 || { echo "Error: cosign not found. Run 'make sign-verify-install' first."; exit 1; }
	@cosign verify \
		--certificate-identity-regexp='https://github.com/firestoned/bindy' \
		--certificate-oidc-issuer='https://token.actions.githubusercontent.com' \
		$(REGISTRY)/$(IMAGE_REPOSITORY):$(IMAGE_TAG) | jq .
	@echo "✓ Image signature verified successfully"

verify-binary: ## Verify binary tarball signature (usage: make verify-binary TARBALL=bindy-linux-amd64.tar.gz)
	@if [ -z "$(TARBALL)" ]; then \
		echo "Error: TARBALL parameter required. Usage: make verify-binary TARBALL=bindy-linux-amd64.tar.gz"; \
		exit 1; \
	fi
	@if [ ! -f "$(TARBALL)" ]; then \
		echo "Error: Tarball not found: $(TARBALL)"; \
		exit 1; \
	fi
	@if [ ! -f "$(TARBALL).bundle" ]; then \
		echo "Error: Signature bundle not found: $(TARBALL).bundle"; \
		exit 1; \
	fi
	@echo "Verifying signature for: $(TARBALL)"
	@command -v cosign >/dev/null 2>&1 || { echo "Error: cosign not found. Run 'make sign-verify-install' first."; exit 1; }
	@cosign verify-blob \
		--bundle "$(TARBALL).bundle" \
		--certificate-identity-regexp='https://github.com/firestoned/bindy' \
		--certificate-oidc-issuer='https://token.actions.githubusercontent.com' \
		"$(TARBALL)"
	@echo "✓ Binary signature verified successfully"

sign-binary: ## Sign a binary tarball locally (requires TARBALL parameter, e.g., make sign-binary TARBALL=bindy-linux-amd64.tar.gz)
	@if [ -z "$(TARBALL)" ]; then \
		echo "Error: TARBALL parameter required. Usage: make sign-binary TARBALL=bindy-linux-amd64.tar.gz"; \
		exit 1; \
	fi
	@if [ ! -f "$(TARBALL)" ]; then \
		echo "Error: Tarball not found: $(TARBALL)"; \
		exit 1; \
	fi
	@echo "Signing tarball: $(TARBALL)"
	@command -v cosign >/dev/null 2>&1 || { echo "Error: cosign not found. Run 'make sign-verify-install' first."; exit 1; }
	@COSIGN_EXPERIMENTAL=1 cosign sign-blob \
		--bundle "$(TARBALL).bundle" \
		"$(TARBALL)"
	@echo "✓ Tarball signed successfully"
	@echo "  - Signature bundle: $(TARBALL).bundle"
