apiVersion: bindy.firestoned.io/v1alpha1
kind: Bind9Cluster
metadata:
  name: production-dns
  namespace: dns-system
spec:
  # Primary instance configuration
  primary:
    # Use NodePort for primary instances (external DNS access)
    service:
      annotations:
        # Example: MetalLB address pool selection
        metallb.universe.tf/address-pool: dns-pool
        # Example: External DNS hostname
        external-dns.alpha.kubernetes.io/hostname: ns1.example.com
      spec:
        type: NodePort
        externalTrafficPolicy: Local

  # Secondary instance configuration
  secondary:
    # Use ClusterIP for secondary instances (internal only)
    service:
      annotations:
        # Example: Linkerd service mesh annotations
        linkerd.io/inject: enabled
      spec:
        type: ClusterIP
        sessionAffinity: ClientIP

  version: "9.18"

  global:
    recursion: false
    allowQuery:
      - "0.0.0.0/0"
    allowTransfer:
      - "10.0.0.0/8"
    dnssec:
      enabled: true
      validation: true
---
apiVersion: bindy.firestoned.io/v1alpha1
kind: Bind9Cluster
metadata:
  name: cloud-dns
  namespace: dns-system
spec:
  # Primary instance configuration
  primary:
    # Use LoadBalancer for primary instances (cloud environments)
    service:
      annotations:
        # Example: AWS load balancer configuration
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: udp
      spec:
        type: LoadBalancer
        loadBalancerIP: "203.0.113.10"  # Optional: specify IP
        externalTrafficPolicy: Local

  # Secondary instance configuration
  secondary:
    # Secondaries also use LoadBalancer for high availability
    service:
      annotations:
        # Example: Azure internal load balancer
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      spec:
        type: LoadBalancer
        externalTrafficPolicy: Cluster

  version: "9.20"

  global:
    recursion: false
    allowQuery:
      - "any"
    dnssec:
      enabled: true
      validation: true
