apiVersion: bindy.firestoned.io/v1beta1
kind: Bind9Instance
metadata:
  name: primary-dns
  namespace: dns-system
  labels:
    dns-role: primary
    environment: production
spec:
  clusterRef: production-dns
  role: primary
  replicas: 2
---
apiVersion: bindy.firestoned.io/v1beta1
kind: Bind9Instance
metadata:
  name: secondary-dns
  namespace: dns-system
  labels:
    dns-role: secondary
    environment: production
spec:
  clusterRef: production-dns
  role: secondary
  replicas: 1
  # For secondary instances, specify primary servers for zone transfers
  primaryServers:
    - "10.0.1.10"  # IP of primary-dns service
