---
# A Records for example.com zone
# Records are associated with DNSZones via labels
# The DNSZone must have a recordsFrom selector that matches these labels

apiVersion: bindy.firestoned.io/v1beta1
kind: ARecord
metadata:
  name: www-example
  namespace: dns-system
  labels:
    zone: example.com
spec:
  name: www
  ipv4Addresses:
    - "192.0.2.1"
  ttl: 300
---
apiVersion: bindy.firestoned.io/v1beta1
kind: ARecord
metadata:
  name: api-example
  namespace: dns-system
  labels:
    zone: example.com
spec:
  name: api
  ipv4Addresses:
    - "192.0.2.2"
  ttl: 300
---
apiVersion: bindy.firestoned.io/v1beta1
kind: ARecord
metadata:
  name: mail-example
  namespace: dns-system
  labels:
    zone: example.com
spec:
  name: mail
  ipv4Addresses:
    - "192.0.2.2"
  ttl: 300
---
# MX Records for example.com zone
apiVersion: bindy.firestoned.io/v1beta1
kind: MXRecord
metadata:
  name: mail-example
  namespace: dns-system
  labels:
    zone: example.com
spec:
  name: "@"
  priority: 10
  mailServer: mail.example.com.
  ttl: 3600
---
# TXT Records for example.com zone
apiVersion: bindy.firestoned.io/v1beta1
kind: TXTRecord
metadata:
  name: spf-example
  namespace: dns-system
  labels:
    zone: example.com
spec:
  name: "@"
  text:
    - "v=spf1 include:_spf.example.com ~all"
  ttl: 3600
---
apiVersion: bindy.firestoned.io/v1beta1
kind: TXTRecord
metadata:
  name: dmarc-example
  namespace: dns-system
  labels:
    zone: example.com
spec:
  name: "_dmarc"
  text:
    - "v=DMARC1; p=reject; rua=mailto:admin@example.com"
  ttl: 3600
---
# CNAME Records for example.com zone
apiVersion: bindy.firestoned.io/v1beta1
kind: CNAMERecord
metadata:
  name: blog-example
  namespace: dns-system
  labels:
    zone: example.com
spec:
  name: blog
  target: www.example.com.
  ttl: 300
---
# Records for internal.local zone
apiVersion: bindy.firestoned.io/v1beta1
kind: ARecord
metadata:
  name: db-internal
  namespace: dns-system
  labels:
    zone: internal.local
spec:
  name: db
  ipv4Addresses:
    - "10.0.1.10"
  ttl: 300
---
apiVersion: bindy.firestoned.io/v1beta1
kind: ARecord
metadata:
  name: app-internal
  namespace: dns-system
  labels:
    zone: internal.local
spec:
  name: app
  ipv4Addresses:
    - "10.0.1.11"
  ttl: 300
---
apiVersion: bindy.firestoned.io/v1beta1
kind: CNAMERecord
metadata:
  name: cache-internal
  namespace: dns-system
  labels:
    zone: internal.local
spec:
  name: cache
  target: db.internal.local.
  ttl: 300
