---
# A Records

# Method 1: Using 'zone' field - matches against DNSZone spec.zoneName
apiVersion: bindy.firestoned.io/v1alpha1
kind: ARecord
metadata:
  name: www-example
  namespace: dns-system
spec:
  zone: example.com  # Matches DNSZone spec.zoneName
  name: www
  ipv4Address: "192.0.2.1"
  ttl: 300
---
# Method 2: Using 'zoneRef' field - references DNSZone by metadata.name (more efficient)
apiVersion: bindy.firestoned.io/v1alpha1
kind: ARecord
metadata:
  name: api-example
  namespace: dns-system
spec:
  zoneRef: example-com  # References DNSZone metadata.name directly
  name: api
  ipv4Address: "192.0.2.2"
  ttl: 300
