---
apiVersion: bindy.firestoned.io/v1alpha1
kind: DNSZone
metadata:
  name: example-com
  namespace: dns-system
spec:
  zoneName: example.com
  # Reference to the Bind9Cluster that manages this zone
  # This must match the Bind9Cluster name, NOT the Bind9Instance name
  clusterRef: production-dns
  nameServerIps:
    ns1.example.com.: 192.168.0.60
  soaRecord:
    primaryNs: ns1.example.com.
    adminEmail: admin.example.com.  # Note: @ replaced with .
    serial: 2024010101
    refresh: 3600
    retry: 600
    expire: 604800
    negativeTtl: 86400
  ttl: 3600
---
apiVersion: bindy.firestoned.io/v1alpha1
kind: DNSZone
metadata:
  name: internal-local
  namespace: dns-system
spec:
  zoneName: internal.local
  # Reference to the Bind9Cluster that manages this zone
  # This must match the Bind9Cluster name, NOT the Bind9Instance name
  clusterRef: production-dns
  nameServerIps:
    ns1.internal.local.: 192.168.0.60
  soaRecord:
    primaryNs: ns1.internal.local.
    adminEmail: admin.internal.local.  # Note: @ replaced with .
    serial: 2024010101
    refresh: 3600
    retry: 600
    expire: 604800
    negativeTtl: 86400
  ttl: 3600
