---
apiVersion: bindy.firestoned.io/v1beta1
kind: DNSZone
metadata:
  name: example-com
  namespace: dns-system
  labels:
    environment: prod
    team: platform
    zone: example.com
spec:
  zoneName: example.com
  # Reference to the Bind9Cluster that manages this zone
  # This must match the Bind9Cluster name, NOT the Bind9Instance name
  # clusterProviderRef: production-dns
  # Instead of referencing cluster or Bind9Instances directly, use label selector to find them.
  bind9InstancesFrom:
    - selector:
        matchLabels:
          app.kubernetes.io/part-of: bindy
          bindy.firestoned.io/cluster: production-dns
          bindy.firestoned.io/managed-by: Bind9Cluster
        matchExpressions:
          - key: bindy.firestoned.io/role
            operator: In
            values:
              - primary
              - secondary
  nameServers:
    - hostname: ns1.example.com.
      ipv4Address: "192.168.0.60"
    - hostname: ns2.example.com.
      ipv4Address: "192.168.0.61"
    - hostname: ns3.example.com.
      ipv4Address: "192.168.0.62"
  recordsFrom:
    - selector:
        matchLabels:
          bindy.firestoned.io/zone: example.com
  soaRecord:
    primaryNs: ns1.example.com.
    adminEmail: admin.example.com.  # Note: @ replaced with .
    serial: 2025012101
    refresh: 3600
    retry: 600
    expire: 604800
    negativeTtl: 86400
  ttl: 3600
# ---
# apiVersion: bindy.firestoned.io/v1beta1
# kind: DNSZone
# metadata:
#   name: cluster-local
#   namespace: dns-system
#   labels:
#     environment: prod
#     team: platform
#     zone: example.com
# spec:
#   zoneName: cluster.local
#   # Reference to the Bind9Cluster that manages this zone
#   # This must match the Bind9Cluster name, NOT the Bind9Instance name
#   # clusterProviderRef: production-dns
#   # Instead of referencing cluster or Bind9Instances directly, use label selector to find them.
#   bind9InstancesFrom:
#     - selector:
#         matchLabels:
#           bindy.firestoned.io/environment: prod
#           bindy.firestoned.io/team: platform
#   nameServerIps:
#     ns1.cluster.local.: 192.168.0.60
#   soaRecord:
#     primaryNs: ns1.cluster.local.
#     adminEmail: admin.cluster.local.  # Note: @ replaced with .
#     serial: 2024010101
#     refresh: 3600
#     retry: 600
#     expire: 604800
#     negativeTtl: 86400
#   ttl: 3600
