// Copyright (c) 2025 Erick Bourgeois, firestoned
// SPDX-License-Identifier: MIT

//! BIND9 Kubernetes resource builders
//!
//! This module provides functions to build Kubernetes resources (Deployment, ConfigMap, Service)
//! for BIND9 instances. All functions are pure and easily testable.

use crate::crd::Bind9Instance;
use k8s_openapi::api::{
    apps::v1::{Deployment, DeploymentSpec},
    core::v1::{
        ConfigMap, Container, ContainerPort, EnvVar, PodSpec, PodTemplateSpec, Probe, Service,
        ServicePort, ServiceSpec, TCPSocketAction, Volume, VolumeMount,
    },
};
use k8s_openapi::apimachinery::pkg::{
    apis::meta::v1::{LabelSelector, ObjectMeta},
    util::intstr::IntOrString,
};
use std::collections::BTreeMap;

/// Builds standardized Kubernetes labels for BIND9 resources.
///
/// Creates a consistent set of labels following Kubernetes best practices,
/// including recommended `app.kubernetes.io/*` labels.
///
/// # Arguments
///
/// * `instance_name` - Name of the Bind9Instance resource
///
/// # Returns
///
/// A BTreeMap of label key-value pairs
///
/// # Example
///
/// ```rust
/// use bindy::bind9_resources::build_labels;
///
/// let labels = build_labels("my-dns-server");
/// assert_eq!(labels.get("app").unwrap(), "bind9");
/// assert_eq!(labels.get("instance").unwrap(), "my-dns-server");
/// ```
pub fn build_labels(instance_name: &str) -> BTreeMap<String, String> {
    let mut labels = BTreeMap::new();
    labels.insert("app".into(), "bind9".into());
    labels.insert("instance".into(), instance_name.into());
    labels.insert("app.kubernetes.io/name".into(), "bind9".into());
    labels.insert("app.kubernetes.io/instance".into(), instance_name.into());
    labels.insert("app.kubernetes.io/component".into(), "dns-server".into());
    labels.insert("app.kubernetes.io/managed-by".into(), "bindy".into());
    labels
}

/// Builds a Kubernetes ConfigMap containing BIND9 configuration files.
///
/// Creates a ConfigMap with:
/// - `named.conf` - Main BIND9 configuration
/// - `named.conf.options` - BIND9 options (recursion, ACLs, DNSSEC, etc.)
///
/// # Arguments
///
/// * `name` - Name for the ConfigMap (typically `{instance-name}-config`)
/// * `namespace` - Kubernetes namespace
/// * `instance` - Bind9Instance spec containing configuration options
///
/// # Returns
///
/// A Kubernetes ConfigMap resource ready for creation/update
pub fn build_configmap(name: &str, namespace: &str, instance: &Bind9Instance) -> ConfigMap {
    let mut data = BTreeMap::new();
    let labels = build_labels(name);

    // Build named.conf
    let named_conf = build_named_conf(instance);
    data.insert("named.conf".into(), named_conf);

    // Build named.conf.options
    let options_conf = build_options_conf(instance);
    data.insert("named.conf.options".into(), options_conf);

    ConfigMap {
        metadata: ObjectMeta {
            name: Some(format!("{}-config", name)),
            namespace: Some(namespace.into()),
            labels: Some(labels),
            ..Default::default()
        },
        data: Some(data),
        ..Default::default()
    }
}

/// Build the main named.conf configuration
fn build_named_conf(_instance: &Bind9Instance) -> String {
    let mut conf = String::new();
    conf.push_str("// BIND9 Configuration - Auto-generated by bindy\n\n");
    conf.push_str("include \"/etc/bind/named.conf.options\";\n");
    conf.push_str("include \"/etc/bind/zones/named.conf.zones\";\n");
    conf.push('\n');

    // Add logging configuration
    conf.push_str("logging {\n");
    conf.push_str("    channel default_log {\n");
    conf.push_str("        stderr;\n");
    conf.push_str("        severity info;\n");
    conf.push_str("        print-time yes;\n");
    conf.push_str("        print-category yes;\n");
    conf.push_str("        print-severity yes;\n");
    conf.push_str("    };\n");
    conf.push_str("    category default { default_log; };\n");
    conf.push_str("    category queries { default_log; };\n");
    conf.push_str("};\n");

    conf
}

/// Build the named.conf.options configuration
fn build_options_conf(instance: &Bind9Instance) -> String {
    let mut conf = String::new();
    conf.push_str("options {\n");
    conf.push_str("    directory \"/var/cache/bind\";\n");
    conf.push_str("    dump-file \"/var/cache/bind/cache_dump.db\";\n");
    conf.push_str("    statistics-file \"/var/cache/bind/named_stats.txt\";\n");
    conf.push_str("    memstatistics-file \"/var/cache/bind/named_mem_stats.txt\";\n");
    conf.push_str("    listen-on { any; };\n");
    conf.push_str("    listen-on-v6 { any; };\n");

    // Recursion setting
    if let Some(config) = &instance.spec.config {
        let recursion = config.recursion.unwrap_or(false);
        conf.push_str(&format!(
            "    recursion {};\n",
            if recursion { "yes" } else { "no" }
        ));

        // Allow-query ACL
        if let Some(allow_query) = &config.allow_query {
            if !allow_query.is_empty() {
                conf.push_str("    allow-query { ");
                for (i, acl) in allow_query.iter().enumerate() {
                    if i > 0 {
                        conf.push_str("; ");
                    }
                    conf.push_str(acl);
                }
                conf.push_str("; };\n");
            }
        }

        // Allow-transfer ACL
        if let Some(allow_transfer) = &config.allow_transfer {
            if !allow_transfer.is_empty() {
                conf.push_str("    allow-transfer { ");
                for (i, acl) in allow_transfer.iter().enumerate() {
                    if i > 0 {
                        conf.push_str("; ");
                    }
                    conf.push_str(acl);
                }
                conf.push_str("; };\n");
            } else {
                conf.push_str("    allow-transfer { none; };\n");
            }
        }

        // DNSSEC configuration
        if let Some(dnssec) = &config.dnssec {
            if dnssec.enabled.unwrap_or(false) {
                conf.push_str("    dnssec-enable yes;\n");
            }
            if dnssec.validation.unwrap_or(false) {
                conf.push_str("    dnssec-validation yes;\n");
            }
        }
    } else {
        // Defaults
        conf.push_str("    recursion no;\n");
        conf.push_str("    allow-transfer { none; };\n");
    }

    conf.push_str("};\n");
    conf
}

/// Builds a Kubernetes Deployment for running BIND9 pods.
///
/// Creates a Deployment with:
/// - BIND9 container using official ISC BIND9 image
/// - ConfigMap volume mounts for configuration
/// - EmptyDir volumes for zones and cache
/// - TCP/UDP port 53 exposed
/// - Liveness and readiness probes
///
/// # Arguments
///
/// * `name` - Name for the Deployment
/// * `namespace` - Kubernetes namespace
/// * `instance` - Bind9Instance spec containing replicas, version, etc.
///
/// # Returns
///
/// A Kubernetes Deployment resource ready for creation/update
pub fn build_deployment(name: &str, namespace: &str, instance: &Bind9Instance) -> Deployment {
    let labels = build_labels(name);
    let replicas = instance.spec.replicas.unwrap_or(1);
    let version = instance.spec.version.as_deref().unwrap_or("9.18");

    Deployment {
        metadata: ObjectMeta {
            name: Some(name.into()),
            namespace: Some(namespace.into()),
            labels: Some(labels.clone()),
            ..Default::default()
        },
        spec: Some(DeploymentSpec {
            replicas: Some(replicas),
            selector: LabelSelector {
                match_labels: Some(labels.clone()),
                ..Default::default()
            },
            template: PodTemplateSpec {
                metadata: Some(ObjectMeta {
                    labels: Some(labels.clone()),
                    ..Default::default()
                }),
                spec: Some(build_pod_spec(name, version)),
            },
            ..Default::default()
        }),
        ..Default::default()
    }
}

/// Build the PodSpec for BIND9
fn build_pod_spec(instance_name: &str, version: &str) -> PodSpec {
    let container = Container {
        name: "bind9".into(),
        image: Some(format!("internetsystemsconsortium/bind9:{}", version)),
        image_pull_policy: Some("IfNotPresent".into()),
        ports: Some(vec![
            ContainerPort {
                name: Some("dns-tcp".into()),
                container_port: 53,
                protocol: Some("TCP".into()),
                ..Default::default()
            },
            ContainerPort {
                name: Some("dns-udp".into()),
                container_port: 53,
                protocol: Some("UDP".into()),
                ..Default::default()
            },
        ]),
        env: Some(vec![EnvVar {
            name: "TZ".into(),
            value: Some("UTC".into()),
            ..Default::default()
        }]),
        volume_mounts: Some(vec![
            VolumeMount {
                name: "config".into(),
                mount_path: "/etc/bind/named.conf".into(),
                sub_path: Some("named.conf".into()),
                ..Default::default()
            },
            VolumeMount {
                name: "config".into(),
                mount_path: "/etc/bind/named.conf.options".into(),
                sub_path: Some("named.conf.options".into()),
                ..Default::default()
            },
            VolumeMount {
                name: "zones".into(),
                mount_path: "/etc/bind/zones".into(),
                ..Default::default()
            },
            VolumeMount {
                name: "cache".into(),
                mount_path: "/var/cache/bind".into(),
                ..Default::default()
            },
        ]),
        liveness_probe: Some(Probe {
            tcp_socket: Some(TCPSocketAction {
                port: IntOrString::Int(53),
                ..Default::default()
            }),
            initial_delay_seconds: Some(30),
            period_seconds: Some(10),
            timeout_seconds: Some(5),
            failure_threshold: Some(3),
            ..Default::default()
        }),
        readiness_probe: Some(Probe {
            tcp_socket: Some(TCPSocketAction {
                port: IntOrString::Int(53),
                ..Default::default()
            }),
            initial_delay_seconds: Some(10),
            period_seconds: Some(5),
            timeout_seconds: Some(3),
            failure_threshold: Some(3),
            ..Default::default()
        }),
        ..Default::default()
    };

    PodSpec {
        containers: vec![container],
        volumes: Some(vec![
            Volume {
                name: "config".into(),
                config_map: Some(k8s_openapi::api::core::v1::ConfigMapVolumeSource {
                    name: Some(format!("{}-config", instance_name)),
                    ..Default::default()
                }),
                ..Default::default()
            },
            Volume {
                name: "zones".into(),
                empty_dir: Some(Default::default()),
                ..Default::default()
            },
            Volume {
                name: "cache".into(),
                empty_dir: Some(Default::default()),
                ..Default::default()
            },
        ]),
        ..Default::default()
    }
}

/// Builds a Kubernetes Service for exposing BIND9 DNS ports.
///
/// Creates a ClusterIP Service exposing:
/// - TCP port 53 (for zone transfers and large queries)
/// - UDP port 53 (for standard DNS queries)
///
/// # Arguments
///
/// * `name` - Name for the Service
/// * `namespace` - Kubernetes namespace
///
/// # Returns
///
/// A Kubernetes Service resource ready for creation/update
pub fn build_service(name: &str, namespace: &str) -> Service {
    let labels = build_labels(name);

    Service {
        metadata: ObjectMeta {
            name: Some(name.into()),
            namespace: Some(namespace.into()),
            labels: Some(labels.clone()),
            ..Default::default()
        },
        spec: Some(ServiceSpec {
            selector: Some(labels),
            ports: Some(vec![
                ServicePort {
                    name: Some("dns-tcp".into()),
                    port: 53,
                    target_port: Some(IntOrString::Int(53)),
                    protocol: Some("TCP".into()),
                    ..Default::default()
                },
                ServicePort {
                    name: Some("dns-udp".into()),
                    port: 53,
                    target_port: Some(IntOrString::Int(53)),
                    protocol: Some("UDP".into()),
                    ..Default::default()
                },
            ]),
            type_: Some("ClusterIP".into()),
            ..Default::default()
        }),
        ..Default::default()
    }
}
