//! BIND9 Kubernetes resource builders
//!
//! This module provides functions to build Kubernetes resources (Deployment, ConfigMap, Service)
//! for BIND9 instances. All functions are pure and easily testable.

use crate::crd::Bind9Instance;
use k8s_openapi::api::{
    apps::v1::{Deployment, DeploymentSpec},
    core::v1::{
        ConfigMap, Container, ContainerPort, EnvVar, PodSpec, PodTemplateSpec, Probe, Service,
        ServicePort, ServiceSpec, TCPSocketAction, Volume, VolumeMount,
    },
};
use k8s_openapi::apimachinery::pkg::{
    apis::meta::v1::{LabelSelector, ObjectMeta},
    util::intstr::IntOrString,
};
use std::collections::BTreeMap;

/// Builds standardized Kubernetes labels for BIND9 resources.
///
/// Creates a consistent set of labels following Kubernetes best practices,
/// including recommended `app.kubernetes.io/*` labels.
///
/// # Arguments
///
/// * `instance_name` - Name of the Bind9Instance resource
///
/// # Returns
///
/// A BTreeMap of label key-value pairs
///
/// # Example
///
/// ```rust
/// use bindy::bind9_resources::build_labels;
///
/// let labels = build_labels("my-dns-server");
/// assert_eq!(labels.get("app").unwrap(), "bind9");
/// assert_eq!(labels.get("instance").unwrap(), "my-dns-server");
/// ```
pub fn build_labels(instance_name: &str) -> BTreeMap<String, String> {
    let mut labels = BTreeMap::new();
    labels.insert("app".to_string(), "bind9".to_string());
    labels.insert("instance".to_string(), instance_name.to_string());
    labels.insert("app.kubernetes.io/name".to_string(), "bind9".to_string());
    labels.insert(
        "app.kubernetes.io/instance".to_string(),
        instance_name.to_string(),
    );
    labels.insert(
        "app.kubernetes.io/component".to_string(),
        "dns-server".to_string(),
    );
    labels.insert(
        "app.kubernetes.io/managed-by".to_string(),
        "bindy-controller".to_string(),
    );
    labels
}

/// Builds a Kubernetes ConfigMap containing BIND9 configuration files.
///
/// Creates a ConfigMap with:
/// - `named.conf` - Main BIND9 configuration
/// - `named.conf.options` - BIND9 options (recursion, ACLs, DNSSEC, etc.)
///
/// # Arguments
///
/// * `name` - Name for the ConfigMap (typically `{instance-name}-config`)
/// * `namespace` - Kubernetes namespace
/// * `instance` - Bind9Instance spec containing configuration options
///
/// # Returns
///
/// A Kubernetes ConfigMap resource ready for creation/update
pub fn build_configmap(name: &str, namespace: &str, instance: &Bind9Instance) -> ConfigMap {
    let mut data = BTreeMap::new();
    let labels = build_labels(name);

    // Build named.conf
    let named_conf = build_named_conf(instance);
    data.insert("named.conf".to_string(), named_conf);

    // Build named.conf.options
    let options_conf = build_options_conf(instance);
    data.insert("named.conf.options".to_string(), options_conf);

    ConfigMap {
        metadata: ObjectMeta {
            name: Some(format!("{}-config", name)),
            namespace: Some(namespace.to_string()),
            labels: Some(labels),
            ..Default::default()
        },
        data: Some(data),
        ..Default::default()
    }
}

/// Build the main named.conf configuration
fn build_named_conf(_instance: &Bind9Instance) -> String {
    let mut conf = String::new();
    conf.push_str("// BIND9 Configuration - Auto-generated by bindy-controller\n\n");
    conf.push_str("include \"/etc/bind/named.conf.options\";\n");
    conf.push_str("include \"/etc/bind/zones/named.conf.zones\";\n");
    conf.push('\n');

    // Add logging configuration
    conf.push_str("logging {\n");
    conf.push_str("    channel default_log {\n");
    conf.push_str("        stderr;\n");
    conf.push_str("        severity info;\n");
    conf.push_str("        print-time yes;\n");
    conf.push_str("        print-category yes;\n");
    conf.push_str("        print-severity yes;\n");
    conf.push_str("    };\n");
    conf.push_str("    category default { default_log; };\n");
    conf.push_str("    category queries { default_log; };\n");
    conf.push_str("};\n");

    conf
}

/// Build the named.conf.options configuration
fn build_options_conf(instance: &Bind9Instance) -> String {
    let mut conf = String::new();
    conf.push_str("options {\n");
    conf.push_str("    directory \"/var/cache/bind\";\n");
    conf.push_str("    dump-file \"/var/cache/bind/cache_dump.db\";\n");
    conf.push_str("    statistics-file \"/var/cache/bind/named_stats.txt\";\n");
    conf.push_str("    memstatistics-file \"/var/cache/bind/named_mem_stats.txt\";\n");
    conf.push_str("    listen-on { any; };\n");
    conf.push_str("    listen-on-v6 { any; };\n");

    // Recursion setting
    if let Some(config) = &instance.spec.config {
        let recursion = config.recursion.unwrap_or(false);
        conf.push_str(&format!(
            "    recursion {};\n",
            if recursion { "yes" } else { "no" }
        ));

        // Allow-query ACL
        if let Some(allow_query) = &config.allow_query {
            if !allow_query.is_empty() {
                conf.push_str("    allow-query { ");
                for (i, acl) in allow_query.iter().enumerate() {
                    if i > 0 {
                        conf.push_str("; ");
                    }
                    conf.push_str(acl);
                }
                conf.push_str("; };\n");
            }
        }

        // Allow-transfer ACL
        if let Some(allow_transfer) = &config.allow_transfer {
            if !allow_transfer.is_empty() {
                conf.push_str("    allow-transfer { ");
                for (i, acl) in allow_transfer.iter().enumerate() {
                    if i > 0 {
                        conf.push_str("; ");
                    }
                    conf.push_str(acl);
                }
                conf.push_str("; };\n");
            } else {
                conf.push_str("    allow-transfer { none; };\n");
            }
        }

        // DNSSEC configuration
        if let Some(dnssec) = &config.dnssec {
            if dnssec.enabled.unwrap_or(false) {
                conf.push_str("    dnssec-enable yes;\n");
            }
            if dnssec.validation.unwrap_or(false) {
                conf.push_str("    dnssec-validation yes;\n");
            }
        }
    } else {
        // Defaults
        conf.push_str("    recursion no;\n");
        conf.push_str("    allow-transfer { none; };\n");
    }

    conf.push_str("};\n");
    conf
}

/// Builds a Kubernetes Deployment for running BIND9 pods.
///
/// Creates a Deployment with:
/// - BIND9 container using official ISC BIND9 image
/// - ConfigMap volume mounts for configuration
/// - EmptyDir volumes for zones and cache
/// - TCP/UDP port 53 exposed
/// - Liveness and readiness probes
///
/// # Arguments
///
/// * `name` - Name for the Deployment
/// * `namespace` - Kubernetes namespace
/// * `instance` - Bind9Instance spec containing replicas, version, etc.
///
/// # Returns
///
/// A Kubernetes Deployment resource ready for creation/update
pub fn build_deployment(name: &str, namespace: &str, instance: &Bind9Instance) -> Deployment {
    let labels = build_labels(name);
    let replicas = instance.spec.replicas.unwrap_or(1);
    let version = instance.spec.version.as_deref().unwrap_or("9.18");

    Deployment {
        metadata: ObjectMeta {
            name: Some(name.to_string()),
            namespace: Some(namespace.to_string()),
            labels: Some(labels.clone()),
            ..Default::default()
        },
        spec: Some(DeploymentSpec {
            replicas: Some(replicas),
            selector: LabelSelector {
                match_labels: Some(labels.clone()),
                ..Default::default()
            },
            template: PodTemplateSpec {
                metadata: Some(ObjectMeta {
                    labels: Some(labels.clone()),
                    ..Default::default()
                }),
                spec: Some(build_pod_spec(name, version)),
            },
            ..Default::default()
        }),
        ..Default::default()
    }
}

/// Build the PodSpec for BIND9
fn build_pod_spec(instance_name: &str, version: &str) -> PodSpec {
    let container = Container {
        name: "bind9".to_string(),
        image: Some(format!("internetsystemsconsortium/bind9:{}", version)),
        image_pull_policy: Some("IfNotPresent".to_string()),
        ports: Some(vec![
            ContainerPort {
                name: Some("dns-tcp".to_string()),
                container_port: 53,
                protocol: Some("TCP".to_string()),
                ..Default::default()
            },
            ContainerPort {
                name: Some("dns-udp".to_string()),
                container_port: 53,
                protocol: Some("UDP".to_string()),
                ..Default::default()
            },
        ]),
        env: Some(vec![EnvVar {
            name: "TZ".to_string(),
            value: Some("UTC".to_string()),
            ..Default::default()
        }]),
        volume_mounts: Some(vec![
            VolumeMount {
                name: "config".to_string(),
                mount_path: "/etc/bind/named.conf".to_string(),
                sub_path: Some("named.conf".to_string()),
                ..Default::default()
            },
            VolumeMount {
                name: "config".to_string(),
                mount_path: "/etc/bind/named.conf.options".to_string(),
                sub_path: Some("named.conf.options".to_string()),
                ..Default::default()
            },
            VolumeMount {
                name: "zones".to_string(),
                mount_path: "/etc/bind/zones".to_string(),
                ..Default::default()
            },
            VolumeMount {
                name: "cache".to_string(),
                mount_path: "/var/cache/bind".to_string(),
                ..Default::default()
            },
        ]),
        liveness_probe: Some(Probe {
            tcp_socket: Some(TCPSocketAction {
                port: IntOrString::Int(53),
                ..Default::default()
            }),
            initial_delay_seconds: Some(30),
            period_seconds: Some(10),
            timeout_seconds: Some(5),
            failure_threshold: Some(3),
            ..Default::default()
        }),
        readiness_probe: Some(Probe {
            tcp_socket: Some(TCPSocketAction {
                port: IntOrString::Int(53),
                ..Default::default()
            }),
            initial_delay_seconds: Some(10),
            period_seconds: Some(5),
            timeout_seconds: Some(3),
            failure_threshold: Some(3),
            ..Default::default()
        }),
        ..Default::default()
    };

    PodSpec {
        containers: vec![container],
        volumes: Some(vec![
            Volume {
                name: "config".to_string(),
                config_map: Some(k8s_openapi::api::core::v1::ConfigMapVolumeSource {
                    name: Some(format!("{}-config", instance_name)),
                    ..Default::default()
                }),
                ..Default::default()
            },
            Volume {
                name: "zones".to_string(),
                empty_dir: Some(Default::default()),
                ..Default::default()
            },
            Volume {
                name: "cache".to_string(),
                empty_dir: Some(Default::default()),
                ..Default::default()
            },
        ]),
        ..Default::default()
    }
}

/// Builds a Kubernetes Service for exposing BIND9 DNS ports.
///
/// Creates a ClusterIP Service exposing:
/// - TCP port 53 (for zone transfers and large queries)
/// - UDP port 53 (for standard DNS queries)
///
/// # Arguments
///
/// * `name` - Name for the Service
/// * `namespace` - Kubernetes namespace
///
/// # Returns
///
/// A Kubernetes Service resource ready for creation/update
pub fn build_service(name: &str, namespace: &str) -> Service {
    let labels = build_labels(name);

    Service {
        metadata: ObjectMeta {
            name: Some(name.to_string()),
            namespace: Some(namespace.to_string()),
            labels: Some(labels.clone()),
            ..Default::default()
        },
        spec: Some(ServiceSpec {
            selector: Some(labels),
            ports: Some(vec![
                ServicePort {
                    name: Some("dns-tcp".to_string()),
                    port: 53,
                    target_port: Some(IntOrString::Int(53)),
                    protocol: Some("TCP".to_string()),
                    ..Default::default()
                },
                ServicePort {
                    name: Some("dns-udp".to_string()),
                    port: 53,
                    target_port: Some(IntOrString::Int(53)),
                    protocol: Some("UDP".to_string()),
                    ..Default::default()
                },
            ]),
            type_: Some("ClusterIP".to_string()),
            ..Default::default()
        }),
        ..Default::default()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crd::{Bind9Config, Bind9InstanceSpec, DNSSECConfig};

    fn create_test_instance(name: &str) -> Bind9Instance {
        Bind9Instance {
            metadata: ObjectMeta {
                name: Some(name.to_string()),
                namespace: Some("test-ns".to_string()),
                ..Default::default()
            },
            spec: Bind9InstanceSpec {
                replicas: Some(2),
                version: Some("9.18".to_string()),
                config: Some(Bind9Config {
                    recursion: Some(false),
                    allow_query: Some(vec!["0.0.0.0/0".to_string()]),
                    allow_transfer: Some(vec!["10.0.0.0/8".to_string()]),
                    dnssec: Some(DNSSECConfig {
                        enabled: Some(true),
                        validation: Some(true),
                    }),
                    forwarders: None,
                    listen_on: None,
                    listen_on_v6: None,
                }),
            },
            status: None,
        }
    }

    #[test]
    fn test_build_labels() {
        let labels = build_labels("test-instance");
        assert_eq!(labels.get("app").unwrap(), "bind9");
        assert_eq!(labels.get("instance").unwrap(), "test-instance");
        assert_eq!(labels.get("app.kubernetes.io/name").unwrap(), "bind9");
        assert_eq!(
            labels.get("app.kubernetes.io/managed-by").unwrap(),
            "bindy-controller"
        );
    }

    #[test]
    fn test_build_configmap() {
        let instance = create_test_instance("test");
        let cm = build_configmap("test", "test-ns", &instance);

        assert_eq!(cm.metadata.name.as_deref(), Some("test-config"));
        assert_eq!(cm.metadata.namespace.as_deref(), Some("test-ns"));

        let data = cm.data.unwrap();
        assert!(data.contains_key("named.conf"));
        assert!(data.contains_key("named.conf.options"));

        let options = data.get("named.conf.options").unwrap();
        assert!(options.contains("recursion no"));
        assert!(options.contains("allow-query { 0.0.0.0/0; }"));
        assert!(options.contains("allow-transfer { 10.0.0.0/8; }"));
        assert!(options.contains("dnssec-enable yes"));
        assert!(options.contains("dnssec-validation yes"));
    }

    #[test]
    fn test_build_deployment() {
        let instance = create_test_instance("test");
        let deployment = build_deployment("test", "test-ns", &instance);

        assert_eq!(deployment.metadata.name.as_deref(), Some("test"));
        assert_eq!(deployment.metadata.namespace.as_deref(), Some("test-ns"));

        let spec = deployment.spec.unwrap();
        assert_eq!(spec.replicas, Some(2));

        let pod_spec = spec.template.spec.unwrap();
        assert_eq!(pod_spec.containers.len(), 1);

        let container = &pod_spec.containers[0];
        assert_eq!(container.name, "bind9");
        assert_eq!(
            container.image.as_deref(),
            Some("internetsystemsconsortium/bind9:9.18")
        );

        let ports = container.ports.as_ref().unwrap();
        assert_eq!(ports.len(), 2);
        assert_eq!(ports[0].container_port, 53);
        assert_eq!(ports[1].container_port, 53);
    }

    #[test]
    fn test_build_service() {
        let service = build_service("test", "test-ns");

        assert_eq!(service.metadata.name.as_deref(), Some("test"));
        assert_eq!(service.metadata.namespace.as_deref(), Some("test-ns"));

        let spec = service.spec.unwrap();
        assert_eq!(spec.type_.as_deref(), Some("ClusterIP"));

        let ports = spec.ports.unwrap();
        assert_eq!(ports.len(), 2);
        assert_eq!(ports[0].port, 53);
        assert_eq!(ports[1].port, 53);
    }

    #[test]
    fn test_named_conf_generation() {
        let instance = create_test_instance("test");
        let conf = build_named_conf(&instance);

        assert!(conf.contains("include \"/etc/bind/named.conf.options\""));
        assert!(conf.contains("include \"/etc/bind/zones/named.conf.zones\""));
        assert!(conf.contains("logging"));
    }

    #[test]
    fn test_options_conf_with_defaults() {
        let instance = Bind9Instance {
            metadata: ObjectMeta {
                name: Some("test".to_string()),
                ..Default::default()
            },
            spec: Bind9InstanceSpec {
                replicas: Some(1),
                version: Some("9.18".to_string()),
                config: None, // No config specified
            },
            status: None,
        };

        let conf = build_options_conf(&instance);
        assert!(conf.contains("recursion no"));
        assert!(conf.contains("allow-transfer { none; }"));
    }

    #[test]
    fn test_options_conf_with_empty_transfer() {
        let instance = Bind9Instance {
            metadata: ObjectMeta {
                name: Some("test".to_string()),
                ..Default::default()
            },
            spec: Bind9InstanceSpec {
                replicas: Some(1),
                version: Some("9.18".to_string()),
                config: Some(Bind9Config {
                    recursion: Some(false),
                    allow_query: None,
                    allow_transfer: Some(vec![]), // Empty transfer list
                    dnssec: None,
                    forwarders: None,
                    listen_on: None,
                    listen_on_v6: None,
                }),
            },
            status: None,
        };

        let conf = build_options_conf(&instance);
        assert!(conf.contains("allow-transfer { none; }"));
    }

    #[test]
    fn test_build_pod_spec() {
        let instance = create_test_instance("test");
        let deployment = build_deployment("test", "test-ns", &instance);
        let pod_spec = deployment.spec.unwrap().template.spec.unwrap();

        // Verify volumes
        let volumes = pod_spec.volumes.unwrap();
        assert_eq!(volumes.len(), 3);
        assert_eq!(volumes[0].name, "config");
        assert_eq!(volumes[1].name, "zones");
        assert_eq!(volumes[2].name, "cache");

        // Verify container configuration
        let container = &pod_spec.containers[0];
        assert_eq!(container.name, "bind9");

        // Verify volume mounts
        let mounts = container.volume_mounts.as_ref().unwrap();
        assert_eq!(mounts.len(), 4);
        assert!(mounts.iter().any(|m| m.name == "config"));
        assert!(mounts.iter().any(|m| m.name == "zones"));
        assert!(mounts.iter().any(|m| m.name == "cache"));

        // Verify probes
        assert!(container.liveness_probe.is_some());
        assert!(container.readiness_probe.is_some());
    }

    #[test]
    fn test_build_deployment_replicas() {
        let mut instance = create_test_instance("test");
        instance.spec.replicas = Some(5);

        let deployment = build_deployment("test", "test-ns", &instance);
        let spec = deployment.spec.unwrap();

        assert_eq!(spec.replicas, Some(5));
    }

    #[test]
    fn test_build_deployment_version() {
        let mut instance = create_test_instance("test");
        instance.spec.version = Some("9.20".to_string());

        let deployment = build_deployment("test", "test-ns", &instance);
        let pod_spec = deployment.spec.unwrap().template.spec.unwrap();
        let container = &pod_spec.containers[0];

        assert_eq!(
            container.image.as_deref(),
            Some("internetsystemsconsortium/bind9:9.20")
        );
    }

    #[test]
    fn test_build_service_ports() {
        let service = build_service("test", "test-ns");
        let spec = service.spec.unwrap();
        let ports = spec.ports.unwrap();

        assert_eq!(ports.len(), 2);

        // Check TCP port
        let tcp_port = ports
            .iter()
            .find(|p| p.name.as_deref() == Some("dns-tcp"))
            .unwrap();
        assert_eq!(tcp_port.port, 53);
        assert_eq!(tcp_port.protocol.as_deref(), Some("TCP"));

        // Check UDP port
        let udp_port = ports
            .iter()
            .find(|p| p.name.as_deref() == Some("dns-udp"))
            .unwrap();
        assert_eq!(udp_port.port, 53);
        assert_eq!(udp_port.protocol.as_deref(), Some("UDP"));
    }

    #[test]
    fn test_configmap_contains_all_files() {
        let instance = create_test_instance("test");
        let cm = build_configmap("test", "test-ns", &instance);

        let data = cm.data.unwrap();
        assert!(data.contains_key("named.conf"));
        assert!(data.contains_key("named.conf.options"));
    }

    #[test]
    fn test_options_conf_with_recursion_enabled() {
        let instance = Bind9Instance {
            metadata: ObjectMeta {
                name: Some("test".to_string()),
                ..Default::default()
            },
            spec: Bind9InstanceSpec {
                replicas: Some(1),
                version: Some("9.18".to_string()),
                config: Some(Bind9Config {
                    recursion: Some(true),
                    allow_query: None,
                    allow_transfer: None,
                    dnssec: None,
                    forwarders: None,
                    listen_on: None,
                    listen_on_v6: None,
                }),
            },
            status: None,
        };

        let conf = build_options_conf(&instance);
        assert!(conf.contains("recursion yes"));
    }

    #[test]
    fn test_options_conf_with_multiple_acls() {
        let instance = Bind9Instance {
            metadata: ObjectMeta {
                name: Some("test".to_string()),
                ..Default::default()
            },
            spec: Bind9InstanceSpec {
                replicas: Some(1),
                version: Some("9.18".to_string()),
                config: Some(Bind9Config {
                    recursion: Some(false),
                    allow_query: Some(vec!["10.0.0.0/8".to_string(), "192.168.0.0/16".to_string()]),
                    allow_transfer: Some(vec![
                        "10.1.0.0/16".to_string(),
                        "10.2.0.0/16".to_string(),
                    ]),
                    dnssec: None,
                    forwarders: None,
                    listen_on: None,
                    listen_on_v6: None,
                }),
            },
            status: None,
        };

        let conf = build_options_conf(&instance);
        assert!(conf.contains("allow-query { 10.0.0.0/8; 192.168.0.0/16; }"));
        assert!(conf.contains("allow-transfer { 10.1.0.0/16; 10.2.0.0/16; }"));
    }

    #[test]
    fn test_labels_consistency() {
        let labels = build_labels("my-instance");

        // Verify all required labels are present
        assert!(labels.contains_key("app"));
        assert!(labels.contains_key("instance"));
        assert!(labels.contains_key("app.kubernetes.io/name"));
        assert!(labels.contains_key("app.kubernetes.io/instance"));
        assert!(labels.contains_key("app.kubernetes.io/component"));
        assert!(labels.contains_key("app.kubernetes.io/managed-by"));

        // Verify label values
        assert_eq!(labels.get("instance").unwrap(), "my-instance");
    }

    #[test]
    fn test_configmap_naming() {
        let instance = create_test_instance("test-instance");
        let cm = build_configmap("test-instance", "test-ns", &instance);

        assert_eq!(cm.metadata.name.as_deref(), Some("test-instance-config"));
        assert_eq!(cm.metadata.namespace.as_deref(), Some("test-ns"));
    }

    #[test]
    fn test_deployment_selector_matches_labels() {
        let instance = create_test_instance("test");
        let deployment = build_deployment("test", "test-ns", &instance);

        let spec = deployment.spec.unwrap();
        let selector_labels = spec.selector.match_labels.unwrap();
        let pod_labels = spec.template.metadata.unwrap().labels.unwrap();

        // Verify selector matches pod labels
        for (key, value) in selector_labels.iter() {
            assert_eq!(pod_labels.get(key), Some(value));
        }
    }

    #[test]
    fn test_service_selector_matches_deployment() {
        let service = build_service("test", "test-ns");
        let deployment_labels = build_labels("test");

        let svc_selector = service.spec.unwrap().selector.unwrap();

        // Verify service selector matches deployment labels
        for (key, value) in svc_selector.iter() {
            assert_eq!(deployment_labels.get(key), Some(value));
        }
    }

    #[test]
    fn test_dnssec_config_enabled() {
        let instance = Bind9Instance {
            metadata: ObjectMeta {
                name: Some("test".to_string()),
                ..Default::default()
            },
            spec: Bind9InstanceSpec {
                replicas: Some(1),
                version: Some("9.18".to_string()),
                config: Some(Bind9Config {
                    recursion: Some(false),
                    allow_query: None,
                    allow_transfer: None,
                    dnssec: Some(DNSSECConfig {
                        enabled: Some(true),
                        validation: Some(false),
                    }),
                    forwarders: None,
                    listen_on: None,
                    listen_on_v6: None,
                }),
            },
            status: None,
        };

        let conf = build_options_conf(&instance);
        assert!(conf.contains("dnssec-enable yes"));
        assert!(!conf.contains("dnssec-validation yes"));
    }

    #[test]
    fn test_dnssec_config_validation_only() {
        let instance = Bind9Instance {
            metadata: ObjectMeta {
                name: Some("test".to_string()),
                ..Default::default()
            },
            spec: Bind9InstanceSpec {
                replicas: Some(1),
                version: Some("9.18".to_string()),
                config: Some(Bind9Config {
                    recursion: Some(false),
                    allow_query: None,
                    allow_transfer: None,
                    dnssec: Some(DNSSECConfig {
                        enabled: Some(false),
                        validation: Some(true),
                    }),
                    forwarders: None,
                    listen_on: None,
                    listen_on_v6: None,
                }),
            },
            status: None,
        };

        let conf = build_options_conf(&instance);
        assert!(!conf.contains("dnssec-enable yes"));
        assert!(conf.contains("dnssec-validation yes"));
    }
}
