#!/bin/bash

# Quick reference for all files in this Bind9 deployment package

echo "📦 Bind9 Kubernetes Cluster - Complete Package"
echo "================================================"
echo ""
echo "✅ Created Files:"
echo ""
echo "📄 CORE MANIFESTS (Deploy these in order)"
echo "  1. namespace.yaml              - Bind9 namespace with Linkerd labels"
echo "  2. rbac.yaml                  - ServiceAccount, Role, RoleBinding"
echo "  3. secret-rndc.yaml           - RNDC authentication key (CHANGE THIS!)"
echo "  4. configmap.yaml             - Bind9 configuration (named.conf, rndc.conf)"
echo "  5. pvc.yaml                   - PersistentVolumeClaims (cache + zones)"
echo "  6. deployment.yaml            - Bind9 Deployment (3 replicas)"
echo "  7. service-dns.yaml           - NodePort 30053 for DNS"
echo "  8. service-rndc.yaml          - ClusterIP for Linkerd/mothership"
echo "  9. service-loadbalancer.yaml  - Optional: LoadBalancer for F5"
echo "  10. networkpolicy.yaml        - Optional: Network policies (prod)"
echo ""
echo "📚 DOCUMENTATION"
echo "  • README.md                   - Complete deployment & troubleshooting guide"
echo "  • DEPLOYMENT.md              - Architecture & overview (THIS FILE)"
echo "  • MOTHERSHIP_INTEGRATION.md  - Bind9 ↔ Mothership integration guide"
echo ""
echo "🔧 SCRIPTS"
echo "  • deploy.sh                  - Automated deployment (chmod +x first)"
echo "  • verify.sh                  - Verification & testing (chmod +x first)"
echo ""
echo "⚙️  CONFIGURATION"
echo "  • kustomization.yaml         - Kustomize configuration"
echo "  • FILE_MANIFEST.sh           - This file"
echo ""
echo "================================================"
echo ""
echo "🚀 QUICK START"
echo ""
echo "Option 1: Automated Deployment"
echo "  chmod +x deploy.sh verify.sh"
echo "  ./deploy.sh dev        # Development"
echo "  ./deploy.sh prod       # Production"
echo "  ./verify.sh            # Verify deployment"
echo ""
echo "Option 2: Manual Deployment"
echo "  kubectl apply -f namespace.yaml"
echo "  kubectl apply -f rbac.yaml"
echo "  kubectl apply -f secret-rndc.yaml"
echo "  kubectl apply -f configmap.yaml"
echo "  kubectl apply -f pvc.yaml"
echo "  kubectl apply -f deployment.yaml"
echo "  kubectl apply -f service-dns.yaml"
echo "  kubectl apply -f service-rndc.yaml"
echo ""
echo "Option 3: Kustomize Deployment"
echo "  kubectl apply -k ."
echo ""
echo "================================================"
echo ""
echo "🔑 CRITICAL: SECURITY STEPS"
echo ""
echo "1. ⚠️  CHANGE RNDC KEY (generate new key)"
echo "   Update in BOTH files:"
echo "   - configmap.yaml (named.conf controls section)"
echo "   - secret-rndc.yaml"
echo ""
echo "2. Review and customize configmap.yaml"
echo "   - Add your zones"
echo "   - Update forwarders if needed"
echo "   - Adjust ACLs for your network"
echo ""
echo "3. For production: Apply networkpolicy.yaml"
echo "   kubectl apply -f networkpolicy.yaml"
echo ""
echo "================================================"
echo ""
echo "📊 RESOURCES PER REPLICA"
echo "  CPU:    250m request  / 1000m limit"
echo "  Memory: 256Mi request / 512Mi limit"
echo "  Storage: 5Gi (cache) + 10Gi (zones)"
echo ""
echo "Total (3 replicas):"
echo "  CPU:    750m request  / 3000m limit"
echo "  Memory: 768Mi request / 1536Mi limit"
echo "  Storage: 15Gi + 30Gi"
echo ""
echo "================================================"
echo ""
echo "🔗 MOTHERSHIP INTEGRATION"
echo ""
echo "See MOTHERSHIP_INTEGRATION.md for:"
echo "  1. Creating ExternalName service in mothership"
echo "  2. Enabling Linkerd mTLS tunneling"
echo "  3. Setting up DNS manager pod"
echo "  4. RNDC commands for zone management"
echo "  5. Troubleshooting guide"
echo ""
echo "================================================"
echo ""
echo "🛠️  COMMON COMMANDS"
echo ""
echo "Verify deployment:"
echo "  kubectl get all -n bind9"
echo ""
echo "View logs:"
echo "  kubectl logs -n bind9 -l app=bind9 -f"
echo ""
echo "Test DNS:"
echo "  kubectl port-forward -n bind9 svc/bind9-dns 5353:53 &"
echo "  dig @127.0.0.1 -p 5353 localhost"
echo ""
echo "RNDC status:"
echo "  POD=\$(kubectl get pods -n bind9 -o jsonpath='{.items[0].metadata.name}')"
echo "  kubectl exec -n bind9 \$POD -- rndc -s 127.0.0.1 -p 953 status"
echo ""
echo "Check PVCs:"
echo "  kubectl get pvc -n bind9"
echo ""
echo "================================================"
echo ""
echo "📞 DOCUMENTATION LINKS"
echo "  • Bind9: https://bind9.readthedocs.io/"
echo "  • k0s: https://docs.k0sproject.io/"
echo "  • Linkerd: https://linkerd.io/"
echo "  • RNDC: https://bind9.readthedocs.io/en/latest/reference/man_rndc.html"
echo ""
echo "================================================"
