apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind9-cache
  namespace: bind9
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # Change based on your k0s storage class
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind9-zones
  namespace: bind9
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # Change based on your k0s storage class
  resources:
    requests:
      storage: 10Gi
